export type Severity = "critical" | "high" | "medium" | "low";
export type Category =
  | "credential_theft"
  | "data_exfiltration"
  | "reverse_shell"
  | "prompt_injection"
  | "zero_width"
  | "shell_execution"
  | "scope_creep"
  | "memory_poisoning"
  | "privacy_risk"
  | "clawhavoc_ioc"
  | "supply_chain"
  | "reconnaissance";

export interface ScanRule {
  id: string;
  category: Category;
  severity: Severity;
  pattern: RegExp;
  description_en: string;
  description_zh: string;
  description_ja: string;
  recommendation_en: string;
  recommendation_zh: string;
  recommendation_ja: string;
}

export const SCAN_RULES: ScanRule[] = [
  // ── CREDENTIAL THEFT ─────────────────────────────────────────────────
  {
    id: "SS-001",
    category: "credential_theft",
    severity: "critical",
    pattern: /cat\s+~\/\.ssh\/id_rsa|read\s+.*\.ssh\/id_rsa|open\s+.*\.ssh\/id_rsa/gi,
    description_en: "Attempts to read SSH private key",
    description_zh: "尝试读取 SSH 私钥",
    description_ja: "SSH秘密鍵の読み取りを試みています",
    recommendation_en: "Legitimate skills never need to read SSH keys.",
    recommendation_zh: "合法技能永远不需要读取 SSH 私钥。",
    recommendation_ja: "正当なスキルはSSHキーを読む必要はありません。",
  },
  {
    id: "SS-002",
    category: "credential_theft",
    severity: "critical",
    pattern: /\$ANTHROPIC_API_KEY|\$OPENAI_API_KEY|\$CLAUDE_API_KEY|\$AWS_SECRET_ACCESS_KEY|\$GOOGLE_API_KEY|\$GITHUB_TOKEN/gi,
    description_en: "References sensitive API key environment variables",
    description_zh: "引用敏感 API 密钥环境变量",
    description_ja: "機密APIキー環境変数を参照しています",
    recommendation_en: "Skills should not access or transmit API keys.",
    recommendation_zh: "技能不应访问或传输 API 密钥。",
    recommendation_ja: "スキルはAPIキーにアクセスまたは送信すべきではありません。",
  },
  {
    id: "SS-003",
    category: "credential_theft",
    severity: "critical",
    pattern: /cat\s+~\/\.env\b|read\s+.*\.env\b|open\s+.*\.env\b|fs\.readFile.*\.env|path\.join.*\.env/gi,
    description_en: "Attempts to read .env file containing environment secrets",
    description_zh: "尝试读取含有环境密钥的 .env 文件",
    description_ja: "環境シークレットを含む.envファイルの読み取りを試みています",
    recommendation_en: "Skills should not access .env files.",
    recommendation_zh: "技能不应访问 .env 文件。",
    recommendation_ja: "スキルは.envファイルにアクセスすべきではありません。",
  },
  {
    id: "SS-004",
    category: "credential_theft",
    severity: "critical",
    pattern: /cat\s+~\/\.netrc|cat\s+~\/\.aws\/credentials|cat\s+~\/\.aws\/config|cat\s+~\/\.kube\/config/gi,
    description_en: "Attempts to read cloud or network credential files",
    description_zh: "尝试读取云服务或网络凭证文件",
    description_ja: "クラウド/ネットワーク資格情報ファイルの読み取りを試みています",
    recommendation_en: "Skills should not read credential files.",
    recommendation_zh: "技能不应读取凭证文件。",
    recommendation_ja: "スキルは資格情報ファイルを読み取るべきではありません。",
  },
  {
    id: "SS-005",
    category: "credential_theft",
    severity: "high",
    pattern: /security\s+find-generic-password|security\s+find-internet-password|keychain-access/gi,
    description_en: "Accesses macOS Keychain credential store",
    description_zh: "访问 macOS 钥匙串（凭证存储）",
    description_ja: "macOSキーチェーン資格情報ストアへのアクセス",
    recommendation_en: "Keychain access is rarely needed by legitimate skills.",
    recommendation_zh: "合法技能很少需要访问钥匙串。",
    recommendation_ja: "正当なスキルがキーチェーンにアクセスする必要はほとんどありません。",
  },
  {
    id: "SS-006",
    category: "credential_theft",
    severity: "critical",
    pattern: /cat\s+~\/\.password-store|pass\s+show|gpg\s+--decrypt.*\.gpg/gi,
    description_en: "Attempts to access password store or decrypt GPG secrets",
    description_zh: "尝试访问密码库或解密 GPG 密钥",
    description_ja: "パスワードストアまたはGPGシークレットへのアクセスを試みています",
    recommendation_en: "Do not allow skills to access password managers.",
    recommendation_zh: "不要允许技能访问密码管理器。",
    recommendation_ja: "スキルがパスワードマネージャーにアクセスすることを許可しないでください。",
  },
  {
    id: "SS-007",
    category: "credential_theft",
    severity: "critical",
    pattern: /process\.env\s*\[|process\.env\.\w*(KEY|SECRET|TOKEN|PASSWORD|PASS|PWD|CRED)/gi,
    description_en: "Accesses sensitive process environment variables via code",
    description_zh: "通过代码访问敏感的进程环境变量",
    description_ja: "コードを通じて機密のプロセス環境変数にアクセスしています",
    recommendation_en: "Skills should not programmatically read secret env vars.",
    recommendation_zh: "技能不应以编程方式读取密钥环境变量。",
    recommendation_ja: "スキルはプログラムでシークレット環境変数を読み取るべきではありません。",
  },
  {
    id: "SS-008",
    category: "credential_theft",
    severity: "high",
    pattern: /git\s+config\s+--global\s+credential|cat\s+~\/\.git-credentials/gi,
    description_en: "Accesses git credential storage",
    description_zh: "访问 git 凭证存储",
    description_ja: "git資格情報ストレージへのアクセス",
    recommendation_en: "Git credentials contain authentication tokens.",
    recommendation_zh: "Git 凭证包含认证令牌，不应被技能访问。",
    recommendation_ja: "git資格情報には認証トークンが含まれています。",
  },
  {
    id: "SS-009",
    category: "credential_theft",
    severity: "critical",
    pattern: /cat\s+~\/\.docker\/config\.json|docker\s+login\s+.*--password/gi,
    description_en: "Accesses Docker registry credentials",
    description_zh: "访问 Docker 注册表凭证",
    description_ja: "Dockerレジストリ資格情報へのアクセス",
    recommendation_en: "Docker config may contain registry authentication tokens.",
    recommendation_zh: "Docker 配置文件可能包含镜像仓库认证令牌。",
    recommendation_ja: "Docker設定にはレジストリ認証トークンが含まれている場合があります。",
  },

  // ── DATA EXFILTRATION ─────────────────────────────────────────────────
  {
    id: "SS-010",
    category: "data_exfiltration",
    severity: "critical",
    pattern: /curl\s+.*webhook\.site|curl\s+.*requestbin|curl\s+.*hookbin|curl\s+.*pipedream\.net/gi,
    description_en: "Data exfiltration to webhook inspection service",
    description_zh: "向 webhook 监听服务外传数据",
    description_ja: "Webhookインスペクションサービスへのデータ漏洩",
    recommendation_en: "This is a classic data exfiltration technique.",
    recommendation_zh: "这是经典的数据外传技术。",
    recommendation_ja: "これは典型的なデータ漏洩技術です。",
  },
  {
    id: "SS-011",
    category: "data_exfiltration",
    severity: "critical",
    pattern: /curl\s+-[A-Za-z]*[dX][A-Za-z]*\s+.*http[s]?:\/\/(?!api\.anthropic|api\.openai|github\.com|registry\.npmjs|pypi\.org)/gi,
    description_en: "HTTP POST to potentially malicious external endpoint",
    description_zh: "向可疑外部端点发送 HTTP POST 请求",
    description_ja: "潜在的に悪意のある外部エンドポイントへのHTTP POST",
    recommendation_en: "Review the destination URL carefully before allowing.",
    recommendation_zh: "请仔细审查目标 URL 再决定是否允许。",
    recommendation_ja: "許可する前に宛先URLを注意深く確認してください。",
  },
  {
    id: "SS-012",
    category: "data_exfiltration",
    severity: "critical",
    pattern: /\|\s*curl\b|\|\s*wget\b|\|\s*nc\s+|\|\s*ncat\s+/gi,
    description_en: "Shell pipe to network tool — data exfiltration pattern",
    description_zh: "通过 Shell 管道将数据传输到网络工具",
    description_ja: "ネットワークツールへのシェルパイプ（データ漏洩パターン）",
    recommendation_en: "Piping data to curl/wget/nc is a classic exfiltration pattern.",
    recommendation_zh: "通过管道将数据传给 curl/wget/nc 是危险的数据外传模式。",
    recommendation_ja: "curl/wget/ncへのパイプはデータ漏洩パターンです。",
  },
  {
    id: "SS-013",
    category: "data_exfiltration",
    severity: "high",
    pattern: /fetch\s*\(\s*['"`]https?:\/\/(?!api\.anthropic|api\.openai|github\.com).*['"`]\s*,\s*\{[^}]*method\s*:\s*['"`]POST['"`]/gi,
    description_en: "Fetch POST to external URL (potential data exfiltration)",
    description_zh: "向外部 URL 发送 Fetch POST 请求（潜在数据外传）",
    description_ja: "外部URLへのFetch POST（潜在的データ漏洩）",
    recommendation_en: "Review what data is being sent and to where.",
    recommendation_zh: "请审查发送的数据内容和目标地址。",
    recommendation_ja: "送信されるデータと送信先を確認してください。",
  },
  {
    id: "SS-014",
    category: "data_exfiltration",
    severity: "high",
    pattern: /XMLHttpRequest|\.send\s*\(|axios\.post|http\.request.*POST/gi,
    description_en: "HTTP POST request via XHR/axios (possible data exfiltration)",
    description_zh: "通过 XHR/axios 发送 HTTP POST 请求（可能的数据外传）",
    description_ja: "XHR/axiosによるHTTP POSTリクエスト（データ漏洩の可能性）",
    recommendation_en: "Verify what data is being transmitted and to where.",
    recommendation_zh: "请确认传输的数据内容和目标地址。",
    recommendation_ja: "送信されるデータと送信先を確認してください。",
  },
  {
    id: "SS-015",
    category: "data_exfiltration",
    severity: "critical",
    pattern: /base64\s+.*\|\s*curl|base64\s+.*\|\s*wget|openssl\s+enc.*\|\s*curl/gi,
    description_en: "Encoded data exfiltration via base64 + curl",
    description_zh: "通过 base64 编码 + curl 进行隐蔽数据外传",
    description_ja: "base64エンコード + curlによるエンコードされたデータ漏洩",
    recommendation_en: "Encoding data before exfiltration is an evasion technique.",
    recommendation_zh: "在外传前编码数据是一种逃避检测的技术。",
    recommendation_ja: "漏洩前のデータエンコードは回避技術です。",
  },
  {
    id: "SS-016",
    category: "data_exfiltration",
    severity: "high",
    pattern: /rsync\s+.*@|scp\s+.*@(?!localhost|127\.)|sftp\s+.*@/gi,
    description_en: "File transfer to remote server via rsync/scp/sftp",
    description_zh: "通过 rsync/scp/sftp 将文件传输到远程服务器",
    description_ja: "rsync/scp/sftpによるリモートサーバーへのファイル転送",
    recommendation_en: "Remote file transfers are rarely needed by legitimate skills.",
    recommendation_zh: "合法技能很少需要向远程服务器传输文件。",
    recommendation_ja: "正当なスキルがリモートファイル転送を必要とすることはほとんどありません。",
  },

  // ── REVERSE SHELL ─────────────────────────────────────────────────────
  {
    id: "SS-020",
    category: "reverse_shell",
    severity: "critical",
    pattern: /bash\s+-i\s+>&\s+\/dev\/tcp/gi,
    description_en: "Bash reverse shell via /dev/tcp",
    description_zh: "通过 /dev/tcp 建立 Bash 反向 Shell",
    description_ja: "/dev/tcpを使用したBashリバースシェル",
    recommendation_en: "This is a classic reverse shell payload. Do not install.",
    recommendation_zh: "这是经典的反向 Shell 载荷，禁止安装。",
    recommendation_ja: "これは典型的なリバースシェルペイロードです。インストールしないでください。",
  },
  {
    id: "SS-021",
    category: "reverse_shell",
    severity: "critical",
    pattern: /nc\s+-e\s+\/bin\/|nc\s+.*-e\s+bash|ncat\s+.*--exec|netcat\s+.*-e/gi,
    description_en: "Netcat reverse shell",
    description_zh: "Netcat 反向 Shell",
    description_ja: "Netcatリバースシェル",
    recommendation_en: "Netcat reverse shell detected. Do not install.",
    recommendation_zh: "检测到 Netcat 反向 Shell，禁止安装。",
    recommendation_ja: "Netcatリバースシェルを検出しました。インストールしないでください。",
  },
  {
    id: "SS-022",
    category: "reverse_shell",
    severity: "critical",
    pattern: /python[23]?\s+-c\s+['"]import\s+socket|python[23]?\s+.*socket\.connect/gi,
    description_en: "Python reverse shell via socket connection",
    description_zh: "Python Socket 反向 Shell",
    description_ja: "PythonソケットによるリバースシェL",
    recommendation_en: "Python reverse shell pattern detected.",
    recommendation_zh: "检测到 Python 反向 Shell 模式。",
    recommendation_ja: "Pythonリバースシェルパターンを検出しました。",
  },
  {
    id: "SS-023",
    category: "reverse_shell",
    severity: "critical",
    pattern: /\/dev\/tcp\/\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\/\d{1,5}/gi,
    description_en: "Direct /dev/tcp connection to IP address (reverse shell)",
    description_zh: "/dev/tcp 直接连接到 IP 地址（反向 Shell）",
    description_ja: "IPアドレスへの直接/dev/tcp接続（リバースシェル）",
    recommendation_en: "Direct TCP connections to IPs indicate reverse shell attempts.",
    recommendation_zh: "直接 TCP 连接到 IP 地址表明存在反向 Shell 尝试。",
    recommendation_ja: "IPへの直接TCP接続はリバースシェルの試みを示します。",
  },
  {
    id: "SS-024",
    category: "reverse_shell",
    severity: "critical",
    pattern: /perl\s+-e\s+['"]use\s+Socket|ruby\s+-rsocket\s+-e|php\s+-r\s+['"].*fsockopen/gi,
    description_en: "Perl/Ruby/PHP reverse shell",
    description_zh: "Perl/Ruby/PHP 反向 Shell",
    description_ja: "Perl/Ruby/PHPリバースシェル",
    recommendation_en: "Scripting language reverse shell detected.",
    recommendation_zh: "检测到脚本语言反向 Shell。",
    recommendation_ja: "スクリプト言語のリバースシェルを検出しました。",
  },
  {
    id: "SS-025",
    category: "reverse_shell",
    severity: "critical",
    pattern: /socat\s+.*exec.*bash|socat\s+tcp.*exec/gi,
    description_en: "Socat reverse shell",
    description_zh: "Socat 反向 Shell",
    description_ja: "Socatリバースシェル",
    recommendation_en: "Socat reverse shell pattern detected.",
    recommendation_zh: "检测到 Socat 反向 Shell 模式。",
    recommendation_ja: "Socatリバースシェルパターンを検出しました。",
  },

  // ── PROMPT INJECTION ──────────────────────────────────────────────────
  {
    id: "SS-030",
    category: "prompt_injection",
    severity: "high",
    pattern: /ignore\s+(all\s+)?(previous|prior|above|earlier)\s+instructions?/gi,
    description_en: "Classic prompt injection: override previous instructions",
    description_zh: "经典提示注入：覆盖之前的指令",
    description_ja: "古典的なプロンプトインジェクション：以前の指示を上書き",
    recommendation_en: "This is a textbook prompt injection pattern.",
    recommendation_zh: "这是教科书级别的提示注入模式。",
    recommendation_ja: "これは典型的なプロンプトインジェクションパターンです。",
  },
  {
    id: "SS-031",
    category: "prompt_injection",
    severity: "high",
    pattern: /disregard\s+(all\s+)?.*instructions?|forget\s+(all\s+)?.*instructions?|override\s+.*instructions?/gi,
    description_en: "Prompt injection: disregard/forget/override instructions",
    description_zh: "提示注入：无视/忘记/覆盖之前指令",
    description_ja: "プロンプトインジェクション：指示の無視/忘却/上書き",
    recommendation_en: "Instruction override patterns indicate prompt injection.",
    recommendation_zh: "指令覆盖模式表明存在提示注入。",
    recommendation_ja: "指示上書きパターンはプロンプトインジェクションを示します。",
  },
  {
    id: "SS-032",
    category: "prompt_injection",
    severity: "high",
    pattern: /you\s+are\s+now\s+(?:a\s+)?(?:DAN|evil|jailbroken|unrestricted|uncensored|free)/gi,
    description_en: "Jailbreak attempt: AI role override",
    description_zh: "越狱尝试：通过角色覆盖绕过限制",
    description_ja: "ジェイルブレイク試行：AIロールオーバーライド",
    recommendation_en: "This tries to override AI safety guardrails.",
    recommendation_zh: "这试图绕过 AI 安全护栏。",
    recommendation_ja: "これはAIの安全ガードレールを回避しようとしています。",
  },
  {
    id: "SS-033",
    category: "prompt_injection",
    severity: "medium",
    pattern: /\[SYSTEM\]|\[INST\]|<\|system\|>|<\|im_start\|>|<\|im_end\|>|<<SYS>>/gi,
    description_en: "LLM instruction delimiter injection",
    description_zh: "LLM 指令分隔符注入",
    description_ja: "LLM命令区切り文字インジェクション",
    recommendation_en: "Embedding LLM delimiters is a prompt injection technique.",
    recommendation_zh: "嵌入 LLM 分隔符是提示注入技术。",
    recommendation_ja: "LLM区切り文字の埋め込みはプロンプトインジェクション技術です。",
  },
  {
    id: "SS-034",
    category: "prompt_injection",
    severity: "high",
    pattern: /act\s+as\s+(?:an?\s+)?(?:AI\s+with\s+no|unrestricted|jailbroken)|pretend\s+(you\s+are|to\s+be)\s+(?:an?\s+)?(?:evil|unrestricted)/gi,
    description_en: "Role-play jailbreak: act as unrestricted AI",
    description_zh: "角色扮演越狱：要求 AI 扮演无限制版本",
    description_ja: "ロールプレイジェイルブレイク：無制限AIとして振る舞う",
    recommendation_en: "This attempts to bypass AI safety through role-play.",
    recommendation_zh: "这试图通过角色扮演绕过 AI 安全措施。",
    recommendation_ja: "ロールプレイでAIの安全性を回避しようとしています。",
  },
  {
    id: "SS-035",
    category: "prompt_injection",
    severity: "medium",
    pattern: /<!-- .*instructions?.*-->|\/\* .*instructions?.*\*\/|<!--hidden|<!--secret/gi,
    description_en: "Hidden instructions in HTML/code comments",
    description_zh: "在 HTML/代码注释中隐藏指令",
    description_ja: "HTML/コードコメントに隠された指示",
    recommendation_en: "Hidden comment instructions are a prompt injection vector.",
    recommendation_zh: "注释中的隐藏指令是提示注入的攻击向量。",
    recommendation_ja: "コメントに隠された指示はプロンプトインジェクションの攻撃ベクターです。",
  },

  // ── SHELL EXECUTION ───────────────────────────────────────────────────
  {
    id: "SS-040",
    category: "shell_execution",
    severity: "high",
    pattern: /\beval\s*\(|\bexec\s*\(|\bos\.system\s*\(|\bos\.popen\s*\(/gi,
    description_en: "Dangerous arbitrary code execution function",
    description_zh: "危险的任意代码执行函数",
    description_ja: "危険な任意コード実行関数",
    recommendation_en: "eval/exec/os.system can execute arbitrary code.",
    recommendation_zh: "eval/exec/os.system 可以执行任意代码。",
    recommendation_ja: "eval/exec/os.systemは任意のコードを実行できます。",
  },
  {
    id: "SS-041",
    category: "shell_execution",
    severity: "high",
    pattern: /subprocess\.(run|call|Popen|check_output)\s*\(.*shell\s*=\s*True/gi,
    description_en: "Python subprocess with shell=True (injection risk)",
    description_zh: "Python subprocess 使用 shell=True（代码注入风险）",
    description_ja: "shell=TrueのPythonサブプロセス（インジェクションリスク）",
    recommendation_en: "shell=True makes subprocess vulnerable to injection.",
    recommendation_zh: "shell=True 使 subprocess 容易受到注入攻击。",
    recommendation_ja: "shell=Trueはサブプロセスをインジェクションに対して脆弱にします。",
  },
  {
    id: "SS-042",
    category: "shell_execution",
    severity: "medium",
    pattern: /rm\s+-rf\s+\/|rm\s+-rf\s+~\/|\bdd\s+if=\/dev\/zero|\bshred\s+/gi,
    description_en: "Destructive file system command",
    description_zh: "破坏性文件系统命令",
    description_ja: "破壊的なファイルシステムコマンド",
    recommendation_en: "This command can permanently delete files.",
    recommendation_zh: "此命令可能永久删除文件。",
    recommendation_ja: "このコマンドはファイルを永久に削除できます。",
  },
  {
    id: "SS-043",
    category: "shell_execution",
    severity: "high",
    pattern: /crontab\s+-[el]|echo\s+.*>>\s*\/etc\/crontab|\/etc\/cron\.(d|daily|hourly)\//gi,
    description_en: "Cron job persistence mechanism",
    description_zh: "通过 cron 建立持久化机制",
    description_ja: "Cronジョブによる永続化メカニズム",
    recommendation_en: "Skills should not create persistent scheduled tasks.",
    recommendation_zh: "技能不应创建持久化的定时任务。",
    recommendation_ja: "スキルは永続的なスケジュールタスクを作成すべきではありません。",
  },
  {
    id: "SS-044",
    category: "shell_execution",
    severity: "high",
    pattern: /chmod\s+[+]?[s].*\/|chown\s+root|sudo\s+.*passwd|passwd\s+root/gi,
    description_en: "Privilege escalation attempt",
    description_zh: "权限提升尝试",
    description_ja: "権限昇格の試み",
    recommendation_en: "Skills should not attempt to escalate privileges.",
    recommendation_zh: "技能不应尝试提升权限。",
    recommendation_ja: "スキルは権限を昇格させようとすべきではありません。",
  },
  {
    id: "SS-045",
    category: "shell_execution",
    severity: "high",
    pattern: /\/bin\/sh\s+-c|\/bin\/bash\s+-c|sh\s+-c\s+['"]/gi,
    description_en: "Shell command injection via -c flag",
    description_zh: "通过 -c 参数进行 Shell 命令注入",
    description_ja: "-cフラグによるシェルコマンドインジェクション",
    recommendation_en: "Shell -c execution with dynamic input is dangerous.",
    recommendation_zh: "使用动态输入的 Shell -c 执行是危险的。",
    recommendation_ja: "動的入力での-cシェル実行は危険です。",
  },
  {
    id: "SS-046",
    category: "shell_execution",
    severity: "medium",
    pattern: /iptables\s+-[FDI]|ufw\s+(disable|allow\s+from\s+any)|firewall-cmd.*--remove/gi,
    description_en: "Firewall rule modification",
    description_zh: "修改防火墙规则",
    description_ja: "ファイアウォールルールの変更",
    recommendation_en: "Firewall modification can expose the system to attacks.",
    recommendation_zh: "修改防火墙规则可能使系统暴露于攻击风险。",
    recommendation_ja: "ファイアウォールの変更はシステムを攻撃にさらす可能性があります。",
  },

  // ── MEMORY POISONING ─────────────────────────────────────────────────
  {
    id: "SS-050",
    category: "memory_poisoning",
    severity: "medium",
    pattern: /always\s+remember\s+that|from\s+now\s+on\s+always|remember\s+this\s+forever|never\s+forget\s+that/gi,
    description_en: "Memory poisoning: persistent instruction injection",
    description_zh: "记忆投毒：持久化指令注入",
    description_ja: "メモリポイズニング：永続的な命令インジェクション",
    recommendation_en: "Attempts to embed persistent instructions in agent memory.",
    recommendation_zh: "试图在 Agent 记忆中嵌入持久化指令。",
    recommendation_ja: "エージェントのメモリに永続的な命令を埋め込もうとしています。",
  },
  {
    id: "SS-051",
    category: "memory_poisoning",
    severity: "medium",
    pattern: /your\s+(new\s+)?(?:core\s+)?instructions?\s+(are|is)\s*:|your\s+(new\s+)?(?:real\s+)?purpose\s+is/gi,
    description_en: "Attempts to replace or redefine agent instructions",
    description_zh: "试图替换或重新定义 Agent 指令",
    description_ja: "エージェントの指示を置き換えまたは再定義しようとしています",
    recommendation_en: "Legitimate skills don't replace agent core instructions.",
    recommendation_zh: "合法技能不会替换 Agent 核心指令。",
    recommendation_ja: "正当なスキルはエージェントのコア指示を置き換えません。",
  },
  {
    id: "SS-052",
    category: "memory_poisoning",
    severity: "medium",
    pattern: /inject.*memory|poison.*context|corrupt.*context|manipulate.*memory/gi,
    description_en: "Explicit memory/context manipulation language",
    description_zh: "明确的记忆/上下文操控描述",
    description_ja: "明示的なメモリ/コンテキスト操作の表現",
    recommendation_en: "Explicit manipulation language is a red flag.",
    recommendation_zh: "明确的操控描述是危险信号。",
    recommendation_ja: "明示的な操作の表現は危険信号です。",
  },

  // ── PRIVACY RISK ─────────────────────────────────────────────────────
  {
    id: "SS-060",
    category: "privacy_risk",
    severity: "low",
    pattern: /access.*contacts|read.*address.?book|get.*phone.?numbers?/gi,
    description_en: "Accesses contact or address book data",
    description_zh: "访问联系人或通讯录数据",
    description_ja: "連絡先またはアドレス帳データへのアクセス",
    recommendation_en: "Verify this skill actually needs contact access.",
    recommendation_zh: "请确认此技能确实需要访问联系人。",
    recommendation_ja: "このスキルが本当に連絡先へのアクセスが必要か確認してください。",
  },
  {
    id: "SS-061",
    category: "privacy_risk",
    severity: "low",
    pattern: /browser.?history|read.*cookies?|access.*location|get.*geolocation/gi,
    description_en: "Accesses browser history, cookies, or location data",
    description_zh: "访问浏览器历史、Cookie 或位置数据",
    description_ja: "ブラウザ履歴、Cookie、または位置情報へのアクセス",
    recommendation_en: "Review why this skill needs browser or location data.",
    recommendation_zh: "请审查此技能为什么需要浏览器或位置数据。",
    recommendation_ja: "このスキルがなぜブラウザまたは位置データを必要とするか確認してください。",
  },
  {
    id: "SS-062",
    category: "privacy_risk",
    severity: "medium",
    pattern: /\/etc\/passwd|\/etc\/shadow|\/etc\/sudoers/gi,
    description_en: "Accesses system user/password files",
    description_zh: "访问系统用户/密码文件",
    description_ja: "システムユーザー/パスワードファイルへのアクセス",
    recommendation_en: "/etc/shadow contains hashed passwords.",
    recommendation_zh: "/etc/shadow 包含哈希密码，不应被技能访问。",
    recommendation_ja: "/etc/shadowにはハッシュされたパスワードが含まれています。",
  },
  {
    id: "SS-063",
    category: "privacy_risk",
    severity: "medium",
    pattern: /find\s+~\s+-name\s+['"*]?\*\.(pdf|doc|docx|xls|xlsx)|ls\s+-la?\s+~\/Documents|ls\s+-la?\s+~\/Desktop/gi,
    description_en: "Enumerates personal document files",
    description_zh: "枚举个人文档文件",
    description_ja: "個人文書ファイルの列挙",
    recommendation_en: "Skills should not scan personal document directories.",
    recommendation_zh: "技能不应扫描个人文档目录。",
    recommendation_ja: "スキルは個人文書ディレクトリをスキャンすべきではありません。",
  },

  // ── SUPPLY CHAIN ─────────────────────────────────────────────────────
  {
    id: "SS-070",
    category: "supply_chain",
    severity: "high",
    pattern: /npm\s+install\s+.*--registry\s+http:\/\/(?!registry\.npmjs\.org)/gi,
    description_en: "npm install from unofficial/custom registry",
    description_zh: "从非官方/自定义注册表安装 npm 包",
    description_ja: "非公式/カスタムレジストリからのnpmインストール",
    recommendation_en: "Custom npm registries can serve malicious packages.",
    recommendation_zh: "自定义 npm 注册表可能提供恶意包。",
    recommendation_ja: "カスタムnpmレジストリは悪意のあるパッケージを提供する可能性があります。",
  },
  {
    id: "SS-071",
    category: "supply_chain",
    severity: "high",
    pattern: /pip\s+install\s+.*--index-url\s+http:\/\/(?!pypi\.org|files\.pythonhosted)/gi,
    description_en: "pip install from unofficial index URL",
    description_zh: "从非官方索引 URL 安装 pip 包",
    description_ja: "非公式インデックスURLからのpipインストール",
    recommendation_en: "Custom pip indices can serve malicious packages.",
    recommendation_zh: "自定义 pip 索引可能提供恶意包。",
    recommendation_ja: "カスタムpipインデックスは悪意のあるパッケージを提供する可能性があります。",
  },
  {
    id: "SS-072",
    category: "supply_chain",
    severity: "medium",
    pattern: /curl\s+.*\|\s*bash|curl\s+.*\|\s*sh\b|wget\s+.*\|\s*bash|wget\s+.*\|\s*sh\b/gi,
    description_en: "Remote script execution via curl/wget pipe to shell",
    description_zh: "通过 curl/wget 管道到 shell 执行远程脚本",
    description_ja: "curl/wgetシェルパイプによるリモートスクリプト実行",
    recommendation_en: "Piping remote scripts to shell is extremely dangerous.",
    recommendation_zh: "将远程脚本直接管道到 shell 执行是极度危险的。",
    recommendation_ja: "リモートスクリプトをシェルにパイプするのは非常に危険です。",
  },
  {
    id: "SS-073",
    category: "supply_chain",
    severity: "high",
    pattern: /docker\s+run\s+.*--privileged|docker\s+run\s+.*-v\s+\/:/gi,
    description_en: "Privileged Docker container or root filesystem mount",
    description_zh: "特权 Docker 容器或根文件系统挂载",
    description_ja: "特権Dockerコンテナまたはルートファイルシステムのマウント",
    recommendation_en: "Privileged containers can compromise the host system.",
    recommendation_zh: "特权容器可能会危及宿主系统。",
    recommendation_ja: "特権コンテナはホストシステムを危険にさらす可能性があります。",
  },

  // ── RECONNAISSANCE ────────────────────────────────────────────────────
  {
    id: "SS-080",
    category: "reconnaissance",
    severity: "medium",
    pattern: /nmap\s+|masscan\s+|zmap\s+|shodan\s+/gi,
    description_en: "Network scanning tool usage",
    description_zh: "使用网络扫描工具",
    description_ja: "ネットワークスキャンツールの使用",
    recommendation_en: "Skills should not perform network reconnaissance.",
    recommendation_zh: "技能不应进行网络侦察。",
    recommendation_ja: "スキルはネットワーク偵察を行うべきではありません。",
  },
  {
    id: "SS-081",
    category: "reconnaissance",
    severity: "medium",
    pattern: /whoami|id\s+-a|uname\s+-a|cat\s+\/etc\/os-release|lsb_release\s+-a/gi,
    description_en: "System information gathering (reconnaissance)",
    description_zh: "收集系统信息（侦察行为）",
    description_ja: "システム情報の収集（偵察）",
    recommendation_en: "System info gathering may indicate reconnaissance.",
    recommendation_zh: "收集系统信息可能表明侦察行为。",
    recommendation_ja: "システム情報の収集は偵察の可能性があります。",
  },
  {
    id: "SS-082",
    category: "reconnaissance",
    severity: "low",
    pattern: /ps\s+aux|ps\s+-ef|netstat\s+-|ss\s+-tuln|lsof\s+-i/gi,
    description_en: "Process and network state enumeration",
    description_zh: "枚举进程和网络状态",
    description_ja: "プロセスとネットワーク状態の列挙",
    recommendation_en: "Process/network enumeration may indicate system mapping.",
    recommendation_zh: "枚举进程和网络状态可能表明系统映射行为。",
    recommendation_ja: "プロセス/ネットワークの列挙はシステムマッピングを示す可能性があります。",
  },

  // ── CLAWHAVOC IOC ─────────────────────────────────────────────────────
  {
    id: "SS-090",
    category: "clawhavoc_ioc",
    severity: "critical",
    pattern: /clawhavoc|claw-havoc|havoc-claw/gi,
    description_en: "ClawHavoc IOC: known malicious skill family reference",
    description_zh: "ClawHavoc IOC：已知恶意技能家族引用",
    description_ja: "ClawHavoc IOC：既知の悪意あるスキルファミリーの参照",
    recommendation_en: "ClawHavoc is a known malicious skill family. Do not install.",
    recommendation_zh: "ClawHavoc 是已知恶意技能家族，请勿安装。",
    recommendation_ja: "ClawHavocは既知の悪意あるスキルファミリーです。インストールしないでください。",
  },
  {
    id: "SS-091",
    category: "clawhavoc_ioc",
    severity: "critical",
    pattern: /attacker\.com|evil\.sh|malware\.site|c2server\.|command-and-control\./gi,
    description_en: "Known malicious domain reference",
    description_zh: "引用已知恶意域名",
    description_ja: "既知の悪意あるドメインの参照",
    recommendation_en: "Known malicious domains detected in skill content.",
    recommendation_zh: "技能内容中检测到已知恶意域名。",
    recommendation_ja: "スキルコンテンツに既知の悪意あるドメインが検出されました。",
  },
];

export const ZERO_WIDTH_CHARS: Record<string, string> = {
  "\u200B": "200B",
  "\u200C": "200C",
  "\u200D": "200D",
  "\uFEFF": "FEFF",
  "\u200E": "200E",
  "\u200F": "200F",
  "\u2060": "2060",
  "\u2061": "2061",
  "\u2062": "2062",
  "\u2063": "2063",
  "\u2064": "2064",
};

export const SEVERITY_SCORES: Record<Severity, number> = {
  critical: 35,
  high: 15,
  medium: 8,
  low: 3,
};
